// Generated by CoffeeScript 1.6.3
(function() {
  var _ref;

  if ((_ref = Q.paths.currentpage) === 'agenzie' || _ref === 'agenti' || _ref === 'poker' || _ref === 'utenti') {
    modulejs.require('initAccounts');
  } else {
    modulejs.require('initFoglinotizia');
  }

}).call(this);
